### ISSUE TITLE
RESULTS

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [MostafaEllethy/music-app#1]
woowwwwwwwwwww what amazing projectttttttttttttttttttttt...many congratulationsssssssssssssssssssssssss dude....but please could you make one button load more to increase unlimited results?I AM BEGGING YOU MY FRIEND!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by MostafaEllethy** [comment]
@KENPOKASMMA1982 Unfortunately, I am using a third-party API that does not allow me to do such a feature. Thank you for your comment appreciated.
